services:
  backend:
    image: food-finder-backend:latest
    container_name: food-finder-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    env_file:
      - ./backend/.env
    restart: unless-stopped
    
    # Use "docker compose watch" for local development
    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend
          target: /app
          action: sync+restart
    
  frontend:
    image: food-finder-frontend:latest
    container_name: food-finder-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:80
    restart: unless-stopped
    
    # Use "docker compose watch" for local development
    develop:
      watch:
        - path: ./frontend
          target: /usr/share/nginx/html
          action: sync+restart